version: '2'
services:
  database:
    container_name: database
    build: 
        context: .
        dockerfile: database/Dockerfile
    ports:
     - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
  mb1:
    container_name: mb1
    depends_on:
      - database 
    build: 
        context: .
        dockerfile: mb1/Dockerfile
    ports:
     - "9773:9763"
     - "9453:9443"
     - "5672:5672"

  mb2:
    container_name: mb2
    depends_on:
      - database 
      - mb1
    build: 
        context: .
        dockerfile: mb2/Dockerfile
    ports:
     - "9783:9763"
     - "9463:9443"
     - "5682:5672"
  esb:
    container_name: esb
    build:
        context: .
        dockerfile: esb/Dockerfile
    ports:
     - "9793:9763"
     - "9473:9443"
     - "8280:8280"
     - "8243:8243"